import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.scss";

const SVNGilroyLight = localFont({ src: "../font/SVNGilroy Light.otf" });
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "suit-media-assignment",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={SVNGilroyLight.className}>{children}</body>
		</html>
	);
}
